version: '2'
services:
  web:
    build: .
    container_name : anguar2-webpack-heroes
    command: npm start
    volumes:
      - .:/angular2/anguar2-webpack-heroes
      - /angular2/anguar2-webpack-heroes/node_modules
    ports:
      - 7006:7006